---
- name: Execute "ls /etc" command
  hosts: staging
  become: yes

  tasks:

  - name: Run "ls /etc" command
    command: ls /etc
    register: ls_command_output

  - name: Show "ls /etc" output
    debug:
      var: ls_command_output.stdout
