---
- name: Install NGINX and copy a simple index.html with text
  hosts: staging
  become: yes

  tasks:
  - name:
    apt:
      update_cache: yes

  - name: Install NGINX
    apt: name=nginx state=present

  - name: Show NGINX is enabled
    service: name=docker state=started enabled=yes

  - name: Create a simple index.html
    copy:
      dest: /var/www/html/index.html
      content: |
          <!DOCTYPE html>
          <html>
          <body>
              <h1>Ansible is the best!</h1>
          </body>
          </html>

  - name: Verify NGINX is running
    shell: curl -s http://localhost
    register: nginx_output

  - name: Show NGINX output
    debug:
      var: nginx_output.stdout